import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
  users: [
    {
      name: "Potzyn",
      email: "potzyn@example.com",
      password: hashSync("123456", 10),
      role: "admin",
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],
  products: [
    // Potted Flowers
    {
      name: "Blooming Lavender Pot",
      slug: "blooming-lavender-pot",
      category: "Flowers",
      description: "Elegant lavender flowers in a decorative pot.",
      images: [
        "/images/sample-products/product-1-1.jpeg",
        "/images/sample-products/product-1-2.jpeg",
      ],
      price: 59.99,
      rating: 4.8,
      numReviews: 256,
      stock: 0,
      isFeatured: true,
    },
    {
      name: "Snake Plant",
      slug: "snake-plant",
      category: "Indoor",
      description: "Perfect for low light and known for improving air quality.",
      images: ["/images/sample-products/product-2.jpeg"],
      price: 182.99,
      rating: 4.7,
      numReviews: 478,
      stock: 9,
      isFeatured: true,
    },
    {
      name: "Colorful Daisy Bouquet Pot",
      slug: "colorful-daisy-bouquet-pot",
      category: "Flowers",
      description: "A vibrant mix of daisies in a rustic pot.",
      images: ["/images/sample-products/product-3.jpeg"],
      price: 249.49,
      rating: 4.6,
      numReviews: 129,
      stock: 10,
      isFeatured: true,
    },
    {
      name: "Japanese Maple Sapling",
      slug: "japanese-maple-sapling",
      category: "Outdoor",
      description: "A stunning tree with vibrant foliage.",
      images: ["/images/sample-products/product-4.jpeg"],
      price: 106.99,
      rating: 4.9,
      numReviews: 255,
      stock: 3,
      isFeatured: false,
    },
    {
      name: "Peace Lily Plant",
      slug: "peace-lily-plant",
      category: "Indoor",
      description: "A low-maintenance plant with air-purifying properties.",
      images: [
        "/images/sample-products/product-5-1.jpeg",
        "/images/sample-products/product-5-2.jpeg",
      ],
      price: 59.99,
      rating: 4.9,
      numReviews: 223,
      stock: 6,
      isFeatured: true,
    },
    {
      name: "Mini Rose Bush",
      slug: "mini-rose-bush",
      category: "Flowers",
      description: "A compact rose plant perfect for brightening your space.",
      images: ["/images/sample-products/product-6.jpeg"],
      price: 343.99,
      rating: 4.7,
      numReviews: 18,
      stock: 8,
      isFeatured: false,
    },
    {
      name: "Fiddle Leaf Fig",
      slug: "fiddle-leaf-fig",
      category: "Indoor",
      description: "A statement plant with broad, glossy leaves.",
      images: ["/images/sample-products/product-7.jpeg"],
      price: 93.99,
      rating: 4.8,
      numReviews: 1485,
      stock: 5,
      isFeatured: true,
    },
    {
      name: "Boxwood Shrub",
      slug: "boxwood-shrub",
      category: "Outdoor",
      description: "Ideal for hedges or decorative garden accents.",
      images: [
        "/images/sample-products/product-8-1.jpeg",
        "/images/sample-products/product-8-2.jpeg",
      ],
      price: 355.99,
      rating: 4.6,
      numReviews: 104,
      stock: 7,
      isFeatured: true,
    },
    {
      name: "Mini Succulent Garden",
      slug: "mini-succulent-garden",
      category: "Indoor",
      description: "A charming set of small succulents.",
      images: [
        "/images/sample-products/product-9-1.jpeg",
        "/images/sample-products/product-9-2.jpeg",
        "/images/sample-products/product-9-3.jpeg",
        "/images/sample-products/product-9-4.jpeg",
      ],
      price: 159.99,
      rating: 4.8,
      numReviews: 2067,
      stock: 35,
      isFeatured: false,
    },
    {
      name: "Lavender Hedge Plant",
      slug: "lavender-hedge-plant",
      category: "Outdoor",
      description: "Fragrant lavender, perfect for garden borders.",
      images: ["/images/sample-products/product-10.jpeg"],
      price: 27.99,
      rating: 4.7,
      numReviews: 16,
      stock: 4,
      isFeatured: true,
    },
    {
      name: "Sunflower Pot",
      slug: "sunflower-pot",
      category: "Flowers",
      description: "Bright sunflowers to light up any space.",
      images: ["/images/sample-products/product-11.jpeg"],
      price: 25.99,
      rating: 4.7,
      numReviews: 190,
      stock: 10,
      isFeatured: true,
    },
    {
      name: "Bonsai Tree",
      slug: "bonsai-tree",
      category: "Indoor",
      description: "A serene miniature tree for your indoor spaces.",
      images: [
        "/images/sample-products/product-12-1.jpeg",
        "/images/sample-products/product-12-2.jpeg",
      ],
      price: 506.99,
      rating: 4.9,
      numReviews: 22,
      stock: 4,
      isFeatured: true,
    },
    {
      name: "Hanging Fern Basket",
      slug: "hanging-fern-basket",
      category: "Outdoor",
      description: "A lush fern perfect for hanging outdoors.",
      images: [
        "/images/sample-products/product-13-1.jpeg",
        "/images/sample-products/product-13-2.jpeg",
      ],
      price: 25.99,
      rating: 4.6,
      numReviews: 1244,
      stock: 10,
      isFeatured: false,
    },
    {
      name: "Mini Monstera",
      slug: "mini-monstera",
      category: "Indoor",
      description: "A stylish mini monstera that thrives in low-light spaces.",
      images: [
        "/images/sample-products/product-14-1.jpeg",
        "/images/sample-products/product-14-2.jpeg",
        "/images/sample-products/product-14-3.jpeg",
      ],
      price: 18.99,
      rating: 4.7,
      numReviews: 2289,
      stock: 15,
      isFeatured: true,
    },
    {
      name: "Terracotta Succulent Set",
      slug: "terracotta-succulent-set",
      category: "Outdoor",
      description:
        "A charming set of succulents in terracotta pots, ideal for patios.",
      images: ["/images/sample-products/product-15.jpeg"],
      price: 869.99,
      rating: 4.8,
      numReviews: 300,
      stock: 20,
      isFeatured: true,
    },
    {
      name: "Dainty Daisy Pot",
      slug: "dainty-daisy-pot",
      category: "Flowers",
      description:
        "Brighten up your space with this adorable pot of white daisies.",
      images: [
        "/images/sample-products/product-16-1.jpeg",
        "/images/sample-products/product-16-2.jpeg",
      ],
      price: 35.99,
      rating: 4.5,
      numReviews: 1892,
      stock: 8,
      isFeatured: true,
    },
    {
      name: "Radiant Rose Pot",
      slug: "radiant-rose-pot",
      category: "Flowers",
      description:
        "A delightful pot of mini roses to add vibrant color to your space.",
      images: [
        "/images/sample-products/product-17-1.jpeg",
        "/images/sample-products/product-17-2.jpeg",
      ],
      price: 215.99,
      rating: 4.7,
      numReviews: 325,
      stock: 6,
      isFeatured: true,
    },
    {
      name: "Mini Bamboo",
      slug: "mini-bamboo",
      category: "Indoor",
      description:
        "A charming mini bamboo plant that brings serenity to any space.",
      images: ["/images/sample-products/product-18.jpeg"],
      price: 182.49,
      rating: 4.9,
      numReviews: 450,
      stock: 12,
      isFeatured: true,
    },
  ],
  blogPosts: [
    {
      title: "How to Care for Ficus",
      createdAt: new Date(),
      updatedAt: new Date(),
      published: true,
      featured: true,
      tag: "Indoor Care",
      sub: "Indoor Plant Care",
      content: "Ficus is one of the most popular indoor plants...",
    },
    {
      title: "Rose Care Guide",
      createdAt: new Date(),
      updatedAt: new Date(),
      published: true,
      featured: true,
      tag: "Outdoor Care",
      sub: "Outdoor Plant Care",
      content: "Roses need proper sunlight and regular watering...",
    },
  ],
  // tags: [
  //   { name: "Indoor Care" },
  //   { name: "Outdoor Care" },
  //   { name: "Flower Care" },
  //   { name: "Pest Control" },
  //   { name: "Plant Styling" },
  //   { name: "Fertilizing" },
  //   { name: "Repotting Tips" },
  //   { name: "Plant Health" },
  //   { name: "Watering Tips" },
  //   { name: "Gardening Tips" },
  // ],
};
export default sampleData;
